// =============================================================================
// Sekans - Seed generator.
// Reads the existing mock data and emits db/seed.sql (utf8mb4 INSERTs) that
// imports cleanly via phpMyAdmin AFTER schema.sql, OR is concatenated into a
// one-time seed.php ($pdo->exec(file_get_contents('seed.sql'))).
//
// RUN LOCALLY (no host shell needed):
//   npx tsx db/generate-seed.mjs          (tsx resolves the .ts import + @/ alias)
//   # or: node --import tsx db/generate-seed.mjs
// Then upload db/seed.sql to phpMyAdmin -> Import.
//
// ID MAPPING: numeric AUTO_INCREMENT ids are assigned deterministically here in
// source order (yazarlar/kategoriler/sayilar) so FKs resolve without round-trips.
// We DISABLE AUTO_INCREMENT guessing by inserting explicit ids.
// =============================================================================
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

// Adjust the import if running outside tsx alias resolution:
import {
  yazarlar, kategoriler, sonSayi, arsivSayilari, araYazilar,
  yarismasiBilgi, hakkimizdaIcerik,
} from '../src/data/mockData.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));

// --- helpers ---------------------------------------------------------------
const q = (v) => {
  if (v === undefined || v === null) return 'NULL';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'boolean') return v ? '1' : '0';
  // MySQL string literal escaping (matches mysql_real_escape_string essentials)
  const s = String(v)
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\x00/g, '\\0')
    .replace(/\x1a/g, '\\Z');
  return `'${s}'`;
};
const slugify = (s) =>
  s.toLowerCase()
    .replace(/ç/g, 'c').replace(/ğ/g, 'g').replace(/ı/g, 'i')
    .replace(/ö/g, 'o').replace(/ş/g, 's').replace(/ü/g, 'u')
    .replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
const isoDate = (s) => (s ? `'${String(s).slice(0, 10)}'` : 'NULL');

// --- deterministic numeric id maps -----------------------------------------
const yazarId = new Map();   // old code -> numeric id
const katIdByCode = new Map();
const katIdByName = new Map(); // ad -> numeric id (for AraYazi string match)
const sayiId = new Map();

const out = [];
out.push('-- Generated by db/generate-seed.mjs. Run after schema.sql.');
out.push('SET NAMES utf8mb4;');
out.push('SET FOREIGN_KEY_CHECKS = 0;');
out.push('START TRANSACTION;');
out.push('');

// --- yazarlar ---------------------------------------------------------------
out.push('-- yazarlar');
yazarlar.forEach((y, i) => {
  const id = i + 1;
  yazarId.set(y.id, id);
  const slug = slugify(y.tamAd);
  out.push(
    `INSERT INTO yazarlar (id, code, ad, soyad, tam_ad, slug, fotograf, biyografi) VALUES ` +
    `(${id}, ${q(y.id)}, ${q(y.ad)}, ${q(y.soyad)}, ${q(y.tamAd)}, ${q(slug)}, ${q(y.fotograf)}, ${q(y.biyografi)});`
  );
});
out.push('');

// --- kategoriler ------------------------------------------------------------
out.push('-- kategoriler');
kategoriler.forEach((k, i) => {
  const id = i + 1;
  katIdByCode.set(k.id, id);
  katIdByName.set(k.ad, id);
  out.push(
    `INSERT INTO kategoriler (id, code, ad, slug, sira_no) VALUES ` +
    `(${id}, ${q(k.id)}, ${q(k.ad)}, ${q(k.slug)}, ${i + 1});`
  );
});
out.push('');

// --- sayilar (current + archive) -------------------------------------------
out.push('-- sayilar');
let sIdx = 0;
const allSayilar = [
  { ...sonSayi, is_current: 1 },
  ...arsivSayilari.map((a) => ({ ...a, is_current: 0 })),
];
allSayilar.forEach((s) => {
  const id = ++sIdx;
  sayiId.set(s.id, id);
  out.push(
    `INSERT INTO sayilar (id, code, numara, ay, yil, tam_baslik, kapak_gorseli, pdf_url, kunye, onsoz, is_current, yayin_tarihi) VALUES ` +
    `(${id}, ${q(s.id)}, ${q(s.numara)}, ${q(s.ay)}, ${s.yil}, ${q(s.tamBaslik)}, ${q(s.kapakGorseli)}, ${q(s.pdfUrl)}, ` +
    `${q(s.kunye)}, ${q(s.onsoz)}, ${s.is_current}, ${isoDate(s.yayinTarihi)});`
  );
});
// Sayı yaşam döngüsü durumu: is_current'ten türet (durum kolonu varsayılanı 'taslak').
out.push("UPDATE sayilar SET durum = IF(is_current = 1, 'yayinda', 'arsiv');");
out.push('');

// --- yazilar (nested in sonSayi.yazilar) ------------------------------------
out.push('-- yazilar (issue articles)');
(sonSayi.yazilar || []).forEach((z, i) => {
  const id = i + 1;
  out.push(
    `INSERT INTO yazilar (id, code, slug, baslik, spot, icerik, yazar_id, kategori_id, sayi_id, sira_no, pdf_url, kapak_gorseli, yayin_tarihi) VALUES ` +
    `(${id}, ${q(z.id)}, ${q(slugify(z.baslik))}, ${q(z.baslik)}, ${q(z.spot)}, ${q(z.icerik)}, ` +
    `${yazarId.get(z.yazar.id)}, ${katIdByCode.get(z.kategori.id)}, ${sayiId.get(z.sayiId)}, ` +
    `${z.siraNo}, ${q(z.pdfUrl)}, ${q(z.kapakGorseli)}, ${isoDate(z.yayinTarihi)});`
  );
});
out.push('');

// --- ara_yazilar (kategori is a NAME string -> resolve to FK) ---------------
out.push('-- ara_yazilar (blog posts)');
araYazilar.forEach((a, i) => {
  const id = i + 1;
  const katId = katIdByName.get(a.kategori); // may be undefined if name not found
  out.push(
    `INSERT INTO ara_yazilar (id, code, slug, baslik, spot, icerik, yazar_id, kategori_id, kategori_ad, kapak_gorseli, yayin_tarihi) VALUES ` +
    `(${id}, ${q(a.id)}, ${q(a.slug)}, ${q(a.baslik)}, ${q(a.spot)}, ${q(a.icerik)}, ` +
    `${yazarId.get(a.yazar.id)}, ${katId ?? 'NULL'}, ${q(a.kategori)}, ${q(a.kapakGorseli)}, ${isoDate(a.yayinTarihi)});`
  );
});
out.push('');

// --- yarisma_bilgi + yarisma_kazananlar -------------------------------------
out.push('-- yarisma_bilgi (singleton)');
out.push(
  `INSERT INTO yarisma_bilgi (id, baslik, aciklama) VALUES (1, ${q(yarismasiBilgi.baslik)}, ${q(yarismasiBilgi.aciklama)}) ` +
  `ON DUPLICATE KEY UPDATE baslik = VALUES(baslik), aciklama = VALUES(aciklama);`
);
out.push('-- yarisma_kazananlar');
(yarismasiBilgi.gecmisKazananlar || []).forEach((k, i) => {
  out.push(
    `INSERT INTO yarisma_kazananlar (id, yil, birinci, ikinci) VALUES ` +
    `(${i + 1}, ${k.yil}, ${q(k.birinci)}, ${q(k.ikinci)});`
  );
});
out.push('');

// --- hakkimizda (singleton, flattened) --------------------------------------
out.push('-- hakkimizda (singleton)');
const h = hakkimizdaIcerik;
out.push(
  `INSERT INTO hakkimizda (id, baslik, icerik, iletisim_email, iletisim_adres, sosyal_twitter, sosyal_instagram, sosyal_facebook) VALUES ` +
  `(1, ${q(h.baslik)}, ${q(h.icerik)}, ${q(h.iletisim.email)}, ${q(h.iletisim.adres)}, ` +
  `${q(h.iletisim.sosyal.twitter)}, ${q(h.iletisim.sosyal.instagram)}, ${q(h.iletisim.sosyal.facebook)}) ` +
  `ON DUPLICATE KEY UPDATE baslik = VALUES(baslik), icerik = VALUES(icerik), iletisim_email = VALUES(iletisim_email), ` +
  `iletisim_adres = VALUES(iletisim_adres), sosyal_twitter = VALUES(sosyal_twitter), ` +
  `sosyal_instagram = VALUES(sosyal_instagram), sosyal_facebook = VALUES(sosyal_facebook);`
);
out.push('');

// --- ayarlar defaults -------------------------------------------------------
// NOTE: The OpenAI API KEY is NEVER stored in the DB — it lives only in the
// above-webroot config.php. We only store the non-secret default model name
// here (shown in the CMS "AI configured" status panel).
out.push('-- ayarlar (key/value defaults; the OpenAI key lives in config.php, NOT here)');
out.push(`INSERT INTO ayarlar (anahtar, deger) VALUES ('openai_model', 'gpt-4o-mini') ON DUPLICATE KEY UPDATE deger = VALUES(deger);`);
out.push('');

out.push('COMMIT;');
out.push('SET FOREIGN_KEY_CHECKS = 1;');
out.push('');

writeFileSync(resolve(__dirname, 'seed.sql'), out.join('\n'), 'utf8');
console.log(`Wrote db/seed.sql with ${araYazilar.length} ara_yazilar, ` +
  `${(sonSayi.yazilar || []).length} yazilar, ${allSayilar.length} sayilar, ` +
  `${yazarlar.length} yazarlar, ${kategoriler.length} kategoriler.`);
